/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jni_update_patch_server_BsDiff */

#ifndef _Included_jni_update_patch_server_BsDiff
#define _Included_jni_update_patch_server_BsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_update_patch_server_BsDiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_update_1patch_server_BsDiff_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
